In [19]:
#Exercici1

import numpy as np

def resum(array):
    if array.ndim > 1:
        print("Error.")
        return
    
    
    print("Mínim:", np.min(array))
    print("Màxim:", np.max(array))
    print("Mitjana:", np.mean(array))
    print("Mediana:", np.median(array))

In [21]:
dades = np.array([1, 2, 3, 4, 5])
resum(dades)

Mínim: 1
Màxim: 5
Mitjana: 3.0
Mediana: 3.0


In [22]:
#Exercici 2

def quadrat(n):
    funcio = np.random.randint(0, 101, size=(n, n))
    return funcio

In [26]:
aleatori = quadrat(5)
print(aleatori)

[[83  0 51 89 25]
 [72 58 23 59  4]
 [37 25 50 50 22]
 [97 26  7 88 85]
 [99 69 69 87 77]]


In [34]:
#Exercici 3

import numpy as np

def total(taula):
    filas = np.sum(taula, axis=1)
    columnes = np.sum(taula, axis=0)
    return filas, columnes

In [35]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

filas, columnes = total(arr)

print("Filas:", filas)
print("Columnes:", columnes)

Filas: [10 26]
Columnes: [ 6  8 10 12]


In [25]:
#Exercici 4

import numpy as np

def coeficient(a,b):
    mitja_a = np.mean(a)
    mitja_b = np.mean(b)
    covarianza = np.sum((a-mitja_a) * (b-mitja_b)) / len(a)
    desv_a = np.std(a)
    desv_b = np.std(b)
    
    correlacio = covarianza / (desv_a * desv_b)
        
    return correlacio   

In [26]:
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]

coef = coeficient(x, y)

print("Coeficient de correlacio:", coef)

Coeficient de correlacio: 0.9999999999999998
